// Filter actions
export const SET_FAV_FILTER = "SET_FAV_FILTER";
export const REMOVE_FAV_FILTER = "REMOVE_FAV_FILTER";
export const SET_PRICE_RANGE = "SET_PRICE_RANGE";
export const SET_DURATION_RANGE = "SET_DURATION_RANGE";
export const SET_LAYOVER_DURATION_RANGE = "SET_LAYOVER_DURATION_RANGE";
export const SET_STOPS_FILTER = "SET_STOPS_FILTER";
export const REMOVE_STOPS_FILTER = "REMOVE_STOPS_FILTER";
export const SET_AIRLINES = "SET_AIRLINES";
export const REMOVE_AIRLINES = "REMOVE_AIRLINES";
export const ADD_COUPON = "ADD_COUPON";

// Trip actions
export const SET_TRIP_TYPE = "SET_TRIP_TYPE";
export const SET_TRIP_FROM = "SET_TRIP_FROM";
export const TOGGLE_FROM_TO_LOCATIONS = "TOGGLE_FROM_TO_LOCATIONS";
export const SET_TRIP_TO = "SET_TRIP_TO";
export const SET_DEPARTURE = "SET_DEPARTURE";
export const SET_RETURN_DATE = "SET_RETURN_DATE";

export const ADD_ANOTHER_TRIP = "ADD_ANOTHER_TRIP";
export const REMOVE_LAST_TRIP = "REMOVE_LAST_TRIP";

export const SET_PASSENGERS_AND_CLASS = "SET_PASSENGERS_AND_CLASS";

// Passengers action types
export const INITIATE_PASSENGERS_FORM = "INITIATE_PASSENGERS_FORM";
export const SET_PASSENGER_DETAIL = "SET_PASSENGER_DETAIL";
export const REMOVE_PASSENGER_DETAIL = "REMOVE_PASSENGER_DETAIL";
export const ADD_NEW_PASSENGER = "ADD_NEW_PASSENGER";

export const UPDATE_GST_DATA = "UPDATE_GST_DATA";
export const UPDATE_CONTACT_DATA = "UPDATE_CONTACT_DATA";

export const SET_SELECTED_FLIGHT_DETAILS = "SET_SELECTED_FLIGHT_DETAILS";

export const SET_SELECTED_SEATS = "SET_SELECTED_SEATS";
export const REMOVE_SELECTED_SEATS = "REMOVE_SELECTED_SEATS";

export const ADD_ADDON = "ADD_ADDON";
export const REMOVE_ADDON = "REMOVE_ADDON";
