name: 'Build'
on: 
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Debugging
        run: |
          echo ${{github.event.pull_request.base.ref}}
      - uses: actions/checkout@v2
      - name: Setup Node 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-=
      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
      - name: Lint
        run: |
          npm run lint
      - name: Replace Build credentials
        run: |
          sed -i "s/http:\/\/localhost:8003\//https:\/\/${{env.CLOUD_FRONT_URL}}\/nextjs\/${GITHUB_SHA::6}/g" next.config.js
          sed -i "s/\"0.0.0\"/\"1.0.0-${GITHUB_SHA::6}\"/g" package.json
          cat next.config.js
        env:
          CLOUD_FRONT_URL: ${{ secrets.CLOUD_FRONT_URL}}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME}}
          CLOUD_FRONT_DISTRIBUTION_ID: ${{ secrets.CLOUD_FRONT_DISTRIBUTION_ID}}
      - name: Build
        run: |
          npm run build

